feat:realizar diseño instrumentos registro
ekisa-desarrollo/esterilizacion pull request #4
Opened 2020-11-17 22:10 UTC by juansechalarca

## Descripción
- Se realizó el diseño del componente instrumento registro.

## Aprobar 

[  ] juan
[  ] sergio
[  ] alexis

2020-11-17 22:26 UTC, juanmesa2097 requested changes

2020-11-17 22:26 UTC, juanmesa2097 commented on client/src/app/admin/containers/instrumentos-registro/instrumentos-registro.page.html
> +          <dx-button text="Guardar" icon="fas fa-save" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"></dx-button>
Le quedó muy chido xD pero debe ser `type="success"` sin clases de tailwind porque los estilos de los controles se deben aplicar desde trumps para que se refleje en todas partes

2020-11-17 22:34 UTC, juanmesa2097 commented on client/src/app/admin/containers/instrumentos-registro/instrumentos-registro.page.html
> +          <dx-button text="Guardar" icon="fas fa-save" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"></dx-button>
Mirando bn el mockup ese botón NO iría porque los registros se guardan desde el datagrid fila por fila. El mockup está mal en ese sentido.

2020-11-18 12:49 UTC, juansechalarca commented on client/src/app/admin/containers/instrumentos-registro/instrumentos-registro.page.html
> +          <dx-button text="Guardar" icon="fas fa-save" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"></dx-button>
yo tambien lo pensé , ese boton ahi esta como chillando, lo quitare inmediatamente.

2020-11-18 13:08 UTC, merged